name: Build PDF

on:
  push:
    branches: 
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build PDF
        id: compile-latex-document
        uses: thomas-chauvet/latex2pdf-action@1.0.1
        with:
          output_dir: build
          main_latex_file: resume.tex
          ctan_packages: koma-script classicthesis currvita hyperref geometry
      - name: Debug print
        run: |
          ls
          ls build
