name: Build PDF

on:
  push:
    branches: 
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build PDF
        id: compile-latex-document
        uses: dante-ev/latex-action@master
        with:
          root_file: resume.tex
      - name: Debug print
        run: |
          ls
          ls build
